name: Node.js CI

on:
  schedule:
    - cron: '0 * 1 * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: install
      run: npm i

    - name: Commit files
      run: |
        git status --porcelain > check.txt
        git ls-files --other --exclude-standard --directory >> check.txt
        echo "testing status"

        if [ -f "check.txt" ]; then
            rm -rf check.txt
            echo "found change commiting"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            echo "config add"
            git add *
            echo "config add"
            git commit -am "AutoUpdate"
            echo "commit add"
            git remote add origin https://github.com/cybemachine/static-server
            git push origin main
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
